version: '3'
services: 
  react-app:
    stdin_open: true
    build: 
      context: . 
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/frontend/node_modules 
      - .:/usr/app/frontend
  react-app-test:
    stdin_open: true
    build: 
      context: . 
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/frontend/node_modules 
      - .:/usr/app/frontend
    command: ["npm","test"]